server:
  port: 7080
  compression:
    enabled: true
  http2:
    enabled: true

logging:
  level:
    com.kafka.producer: debug
#    org.springframework.kafka: debug

spring:
  application:
    name: producer-service

  kafka:
    bootstrap-servers: localhost:9092

    properties:
      schema.registry.url: http://localhost:8081

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
